### ISSUE TITLE
Notifications too?

### ISSUE THREAD

**Issue by forteller** [ipaq3870/gsext-transparentosd#1]
Thank you, I love this!

Would it be possible to add the option to add transparency to the notifications on the top of the screen too?

**Comment by ipaq3870** [comment]
This should belong to another extension rather than gsext-transparent-osd. I created one which should be found here when approved: https://extensions.gnome.org/extension/1080/transparent-notification/ . Meanwhile you can get it from https://github.com/ipaq3870/gsext-transparent-notification
